### ISSUE TITLE
按需引入 Button，但打包后，还是把所有组件都打包进去了

### ISSUE THREAD

**Issue by didiaohu** [Tyh2001/tyh-ui2#33]
我想按需引入 Button，最终打包结果就是 Button；按需引入 Card，最终打包结果就只有 Card。但现在情况是无论按需引入什么组件，都把所有组件都打包了。

**Comment by didiaohu** [comment]
请问下群主有微信群？

**Comment by Tyh2001** [comment]
> 请问下群主有微信群？

我 GitHub 首页可以加我微信，拉你进群
